# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rockerboo.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: rockerBOO (Blog)
  avatar: face200-circle.jpg
  gravatar: # b211c51e10480839982718365a067821 # Email MD5 hash
  description: "Writings about web development from a ten year veteran talking about front and backend development." # used by search engines

  # Header and footer text
  header_text: >
     <p>Ten years working on large scale web applications.</p>

  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: rockerboo@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr: rockerboo
  github: rockerboo
  google_plus:
  instagram: rockerboo
  linkedin: http://linkedin.com/in/rockerboo # Full URL
  pinterest:
  reddit: rockerboo
  soundcloud:
  stack_exchange:  # Full URL
  steam: rockerboo
  tumblr:
  twitter: "twitter"
  wordpress:
  youtube: rockerboo

  # Scripts
  google_analytics: UA-2334636-13 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
